version: '3.8'

services:
  fire_postgres:
    image: postgres
    container_name: fire_postgres
    read_only: true
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user123
      - POSTGRES_DB=fireDb
    expose:
      - "54322"
    ports:
      - "54322:54322"
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    command: -p 54322

  fire_emergency_app:
    image: 'fire_emergency_app'
    container_name: fire_emergency_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - fire_postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fire_postgres:54322/fireDb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_FLYWAY_URL=jdbc:postgresql://fire_postgres:54322/fireDb
      - SPRING_FLYWAY_USER=user
      - SPRING_FLYWAY_PASSWORD=user123
      - SPRING_FLYWAY_BASELINE_ON_MIGRATE=true
    ports:
      - "8081:8080"


volumes:
  postgres-volume:

